stages:
  - build
  - deploy

variables:
  XXX: foo bar

include:
  - project: 'mall/ci'
    ref: master
    file: '/build.yml'
  - project: 'mall/ci'
    ref: master
    file: '/deploy.yml'

build:
  stage: build
  script: echo awesome build $XXX
