
stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: echo Build!

test1:
  stage: test
  script: echo Test1!
  when: always

deploy:
  stage: deploy
  script: echo Deploy!
  when: manual
