image: ondrejsika/ci

job:
  script: env | grep KUBE

job_dev:
  environment:
    name: dev/foo
  script: env | grep KUBE


job_prod:
  environment:
    name: prod
    url: https://$CI_PROJECT_PATH_SLUG.$KUBE_INGRESS_BASE_DOMAIN 
  script:
    - helm repo add ondrejsika https://helm.oxs.cz
    - helm upgrade --install hello ondrejsika/one-image --set host=$CI_PROJECT_PATH_SLUG.$KUBE_INGRESS_BASE_DOMAIN 
