pipeline_a:
  trigger:
    include: a/.gitlab-ci.yml
    strategy: depend

pipeline_b:
  trigger:
    include: b/.gitlab-ci.yml
    strategy: depend

staging:
  allow_failure: true
  trigger: 
    project: mall/foo
