image: ondrejsika/ci

stages:
  - build
  - deploy dev
  - test dev
  - deploy prod
  - test prod

variables:
  IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA

.deploy: &deploy
  script:
    - helm repo add ondrejsika https://helm.oxs.cz
    - helm upgrade --install $CI_PROJECT_PATH_SLUG ondrejsika/one-image
      --set image=$IMAGE
      --set host=$HOST

build:
  stage: build
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t $IMAGE .
    - docker push $IMAGE

deploy dev:
  <<: *deploy
  stage: deploy dev
  variables:
    HOST: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.$KUBE_INGRESS_BASE_DOMAIN
  environment:
    name: dev/$CI_COMMIT_REF_SLUG
    url: https://$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.$KUBE_INGRESS_BASE_DOMAIN
    on_stop: stop dev

stop dev:
  stage: deploy dev
  variables:
    GIT_STRATEGY: none
  script:
    - helm uninstall $CI_PROJECT_PATH_SLUG
  when: manual
  environment:
    name: dev/$CI_COMMIT_REF_SLUG
    action: stop

test dev:
  stage: test dev
  script:
    - curl https://$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.$DEV_KUBE_INGRESS_BASE_DOMAIN

deploy prod:
  <<: *deploy
  only:
    - master
  when: manual
  allow_failure: false
  stage: deploy prod
  variables:
    HOST: $CI_PROJECT_PATH_SLUG.$KUBE_INGRESS_BASE_DOMAIN
  environment:
    name: prod
    url: https://$CI_PROJECT_PATH_SLUG.$KUBE_INGRESS_BASE_DOMAIN

test prod:
  stage: test prod
  script:
    - curl https://$CI_PROJECT_PATH_SLUG.$PROD_KUBE_INGRESS_BASE_DOMAIN
