stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: echo build
  only:
    - branches
    - merge_request

test:
  stage: test
  script: echo test
  only:
    - merge_request

deploy:
  stage: deploy
  script: echo deploy
  only:
    - master
